- qfunctionconfigurator/functionconfig.cpp
Because i used the curves to amplify the output considerably, the nearest neighbor lookup resulted in jagged movement. This is much better.
> Linear Interpolation of Mapping Curves

- ftnoir_tracker_hatire/ftnoir_hatcontrols.ui
- ftnoir_tracker_hatire/ftnoir_tracker_hat.cpp
- ftnoir_tracker_hatire/ftnoir_tracker_hat.h
- ftnoir_tracker_hatire/ftnoir_tracker_hat_dialog.cpp
- ftnoir_tracker_hatire/ftnoir_tracker_hat_dialog.h
- ftnoir_tracker_hatire/ftnoir_tracker_hat_settings.cpp
- ftnoir_tracker_hatire/ftnoir_tracker_hat_settings.h
Pull request that address the bugs found so far under the hatire plugin issues.
> Fix returning consistent data to get headpose and other minor issues

- facetracknoir/main.cpp
- facetracknoir/ui.cpp
- facetracknoir/ui.h
Proposed fix for #159 
EDIT: Fixed incorrect issue reference.
> Added command line option for automatic starts

- gui/options-dialog.cpp
- gui/options-dialog.hpp
- gui/settings.ui
- gui/ui.cpp
- gui/ui.h
- opentrack-logic/main-settings.hpp
- opentrack-logic/state.hpp
- opentrack-logic/tracker.cpp
- opentrack-logic/tracker.h
- opentrack-logic/tracklogger.cpp
- opentrack-logic/tracklogger.hpp
- opentrack-logic/work.cpp
- opentrack-logic/work.hpp
This is probably worthy of a pull request. I hope the capability to log pose data will be useful not just for me.
Btw., I replaced my previous branch of the same name due to the rebase.
> Track Logging

- filter-kalman/kalman.h
Just a minor change: More deadzone when KF is unsure of the model. Still gives very smooth motion when head pose changes at near constant velocity.
> filter-kalman parameter tuning

- gui/lang/ru_RU.ts
> gui: initial Russian translation

- gui/lang/nl_NL.ts
> Initial Dutch translations

- qxt-mini/qxtglobalshortcut_x11.cpp
> Linux/X11: Fix hotkeys

- proto-iokit-foohid/CMakeLists.txt
- proto-iokit-foohid/README.md
- proto-iokit-foohid/foohidjoystick.cpp
- proto-iokit-foohid/foohidjoystick.h
- proto-iokit-foohid/iokitprotocol.cpp
- proto-iokit-foohid/iokitprotocol.h
- proto-iokit-foohid/iokitprotocoldialog.cpp
- proto-iokit-foohid/iokitprotocoldialog.h
- proto-iokit-foohid/lang/nl_NL.ts
- proto-iokit-foohid/lang/ru_RU.ts
- proto-iokit-foohid/lang/stub.ts
Based of the foohid IOKit driver for implementing virtual HID devices.
Issue: #236
> Add virtual joystick output for macOS

- README.md
There is a separate fork on opentrack/aruco nowadays.
Issue: #697
> Fix ArUco source link in README

- tracker-pt/tracker-wii/wii_camera.cpp
- tracker-pt/tracker-wii/wii_camera.h
- tracker-pt/tracker-wii/wii_frame.cpp
- tracker-pt/tracker-wii/wii_frame.hpp
- tracker-pt/tracker-wii/wii_module.cpp
- tracker-pt/tracker-wii/wii_point_extractor.cpp
- tracker-pt/tracker-wii/wii_point_extractor.h
1. fix horizon line drawing
2. fix copyright
3. optimize pointer mangement
4. reduce wii led power consumption
> tracker/wii: update according to Issue: #718 suggestion from sthalik

- tracker-wii/lang/zh_CN.ts
- tracker-wii/wii_camera.cpp
I added chinese lang firstly. but it doesnt take effect
#718
> tracker/wii: add lang chinese && BT optimization

- tracker-wii/wii_module.cpp
#718 @sthalik yes you are right
> tracker/wii: remove UI setting dialog tab0

- gui/lang/zh_CN.ts
- tracker-pt/lang/zh_CN.ts
- variant/default/lang/zh_CN.ts
> add Chinese Lang

- tracker-wii/wiiyourself/wiimote.cpp
@sthalik I hope it doesnt conflict with your local clang format change
> wiiyourself: clang format

- gui/lang/zh_CN.ts
> gui: update Chinese translation

- tracker-pt/point_tracker.cpp
Tracking for caps was broken.
Issue: #854, #822
Reported by: @Attigliuzzo, listekcr
> tracker/pt: fix evil typo

- tracker-kinect-face/kinect_face_settings.ui
- tracker-kinect-face/lang/nl_NL.ts
- tracker-kinect-face/lang/ru_RU.ts
- tracker-kinect-face/lang/stub.ts
- tracker-kinect-face/lang/zh_CN.ts
> Kinect Tracker settings now showing telemetry notice as per EULA.

- options/tie.cpp
- options/tie.hpp
- tracker-easy/lang/nl_NL.ts
- tracker-easy/lang/ru_RU.ts
- tracker-easy/lang/stub.ts
- tracker-easy/lang/zh_CN.ts
- tracker-easy/module.cpp
- tracker-easy/point-extractor.cpp
- tracker-easy/point-extractor.h
- tracker-easy/preview.cpp
- tracker-easy/preview.h
- tracker-easy/settings.h
- tracker-easy/tracker-easy-dialog.cpp
- tracker-easy/tracker-easy-dialog.h
- tracker-easy/tracker-easy-settings.ui
- tracker-easy/tracker-easy.cpp
- tracker-easy/tracker-easy.h
Easy Tracker: Adding support for four and five points models.
Adding basic bad pose filtering.
Auto center feature.
> Easy tracker more models

- tracker-easy/tracker-easy.cpp
Was mostly affecting color cameras.
Not attempting to extract points from color buffer any more.
> Easy Tracker: Fixing deadlock occurring after changing ticker timer interval

- tracker-easy/point-extractor.cpp
- tracker-easy/preview.cpp
- tracker-easy/tracker-easy.cpp
- tracker-easy/tracker-easy.h
> Easy Tracker: Fix #945 trivial warnings.

- AUTHORS.md
- OPENTRACK-LICENSING.txt
- README.md
> Update author, readme & licensing

- tracker-easy/lang/nl_NL.ts
- tracker-easy/lang/ru_RU.ts
- tracker-easy/lang/stub.ts
- tracker-easy/lang/zh_CN.ts
- tracker-easy/module.cpp
- tracker-easy/settings.h
- tracker-easy/tracker-easy-dialog.cpp
- tracker-easy/tracker-easy-settings.ui
- tracker-easy/tracker-easy.cpp
- tracker-easy/tracker-easy.h
Adding support for Clip models where three vertices are arranged from top to bottom.
Close #1145
> tracker/easy: Adding support for Clip models

- tracker-tobii/CMakeLists.txt
- tracker-tobii/ftnoir_tracker_tobii.cpp
- tracker-tobii/ftnoir_tracker_tobii.h
- tracker-tobii/ftnoir_tracker_tobii_controls.ui
- tracker-tobii/ftnoir_tracker_tobii_dialog.cpp
- tracker-tobii/lang/nl_NL.ts
- tracker-tobii/lang/ru_RU.ts
- tracker-tobii/lang/stub.ts
- tracker-tobii/lang/zh_CN.ts
- tracker-tobii/thread.cpp
- tracker-tobii/thread.hpp
Please review and suggest how to improve.
> WIP Tobii Eye tracker support.

- opentrack/main-window.ui
- pose-widget/pose-widget.cpp
Fixed the sizes of the widgets in the main window. Removed the background fill in the pose-widget to better match the dark theme.
> Fixed the sizes of the widgets in the main window

- .github/workflows/cmake.yml
- .github/workflows/cmake_tags.yml
Hi Stanislaw Halik,
this is a beginning commit of auto-build Github workflow, I hope release can be done automatically in the future
> win/macos/lin auto build: add workflows

- tracker-neuralnet/ftnoir_tracker_neuralnet.cpp
- tracker-neuralnet/ftnoir_tracker_neuralnet.h
- tracker-neuralnet/lang/nl_NL.ts
- tracker-neuralnet/lang/ru_RU.ts
- tracker-neuralnet/lang/stub.ts
- tracker-neuralnet/lang/zh_CN.ts
- tracker-neuralnet/neuralnet-trackercontrols.ui
- Added support for MJPEG compression for neuralnet tracker
> Added support for MJPEG compression for neuralnet

- tracker-neuralnet/ftnoir_tracker_neuralnet.cpp
- tracker-neuralnet/ftnoir_tracker_neuralnet.h
- tracker-neuralnet/lang/nl_NL.ts
- tracker-neuralnet/lang/ru_RU.ts
- tracker-neuralnet/lang/stub.ts
- tracker-neuralnet/lang/zh_CN.ts
- tracker-neuralnet/neuralnet-trackercontrols.ui
@sthalik , as promised.
It's a bit big so I left the individual commits instead of squashing.
There are some nice changes, I guess. :-)
Please test if possible because I changed how the face region is determined during tracking.
Been experimenting with recurrent neural nets, hence the support for those. But still I haven't found something that I like more than the released net.
> Neuralnet Tracker Improvements

- cmake/FindONNXRuntime.cmake
Is it convenient for you @sthalik ?
I tested it on Linux with the onnx `onnxruntime-linux-x64-*.tgz ` release archive and on Windows x86 with the nuget package.
> tracker/nn: Let cmake script support a greater variety of ONNX installs

- tracker-neuralnet/lang/ru_RU.ts
Russian translation for Neuralnet tracker
> tracker-neuralnet: russian translation

- proto-wine/ftnoir_protocol_wine.cpp
- proto-wine/ftnoir_protocol_wine.h
- proto-wine/ftnoir_protocol_wine_dialog.cpp
- proto-wine/ftnoir_winecontrols.ui
- proto-wine/lang/nl_NL.ts
- proto-wine/lang/ru_RU.ts
- proto-wine/lang/stub.ts
- proto-wine/lang/zh_CN.ts
new branch
old [PR](https://github.com/opentrack/opentrack/pull/1619)
This only contains the changes done to the UI of the proto-wine module.
> RFC: proto-wine UI changes second attempt

- proto-wine/ftnoir_protocol_wine.h
https://github.com/opentrack/opentrack/pull/1620
we missed one Star Citizen reference
> remove Star Citizen refrence from recent PR

- filter-ewma2/ftnoir_ewma_filtercontrols.ui
- filter-ewma2/ftnoir_filter_ewma2.cpp
- filter-ewma2/ftnoir_filter_ewma2.h
- filter-ewma2/lang/nl_NL.ts
- filter-ewma2/lang/ru_RU.ts
- filter-ewma2/lang/stub.ts
- filter-ewma2/lang/zh_CN.ts
EWMA has a smoothing function with a time constant of 60s. This means that the filter has to run for a time on the order of 60s before it really starts to work.
This PR reduces the time constant when the filter starts so that it resolves a lot faster. Full accuracy will still take on the order of 60s but that is a marginal gain whereas an early estimate of the smoothed position value has a noticeable positive effect.
There are also a few minor code cleanups and efficiency improvements, including not applying the -180° to 180° logic for linear axes.
> Faster settle time for EWMA

- filter-nm/lang/zh_CN.ts
- gui/lang/zh_CN.ts
- tracker-neuralnet/lang/zh_CN.ts
> translate¿

- tracker-neuralnet/model_adapters.h
Hi @sthalik ,
just a small change. FYI, since I don't want to just push into upstream.
Cheers
> tracker/nn: Fix compile error with old onnx version

- gui/lang/zh_CN.ts
- tracker-aruco/lang/zh_CN.ts
Tracker-Aruco 's translation.  
And some minor changes to the main GUI.
> Tracker-Aruco 's translation.

- gui/lang/zh_CN.ts
- tracker-neuralnet/ftnoir_tracker_neuralnet.cpp
- tracker-neuralnet/ftnoir_tracker_neuralnet.h
- tracker-neuralnet/lang/nl_NL.ts
- tracker-neuralnet/lang/ru_RU.ts
- tracker-neuralnet/lang/stub.ts
- tracker-neuralnet/lang/zh_CN.ts
- tracker-neuralnet/neuralnet-trackercontrols.ui
Hi,
this PR adds a button to the neuralnet tracker to chose the onnx file for the pose network.
It's meant for developers/me for more convenient experimentation because renaming and replacing the file is tiresome and error prone.
> tracker/nn: Add button to choose pose net file

- filter-accela/lang/zh_CN.ts
- filter-ewma2/ftnoir_ewma_filtercontrols.ui
- filter-ewma2/lang/zh_CN.ts
- filter-hamilton/lang/zh_CN.ts
- filter-kalman/lang/zh_CN.ts
> Filter translation

- logic/lang/zh_CN.ts
- proto-mouse/lang/zh_CN.ts
- tracker-s2bot/lang/zh_CN.ts
- tracker-tobii/lang/zh_CN.ts
- video-ps3eye/lang/zh_CN.ts
logic/  
proto-mouse/  
tracker-s2bot/  
tracker-tobii/  
video-ps3eye/
> Some translations

- video-ps3eye/shm-layout.hpp
> video-ps3eye: Fix compilation with clang

- tracker-neuralnet/ftnoir_tracker_neuralnet.cpp
Hi guys,
I think there might have been a little bug since the beginning in the NN tracker ...
Roll is now (hopefully) computed from the correct matrix. It turns out it was using values from row 2 instead of 1. Makes more sense to measure roll based on the y-component of local axes. Must have slipped in the matrix row somehow. Reference to wikipedia is added.
Only noticed now where I experimented with centering methods and a model which can handle large yaws. Somehow the previous roll computation was working okay for smallish yaw. Near 90 deg it outputted garbage.
> tracker/nn: Fix roll output
