opentrack/opentrack

CMakeLists.txt
opentrack/plugin-support.hpp
x-plane-plugin/plugin.c

* Replaced `XPLMRegisterDrawCallback` with ` XPLMRegisterFlightLoopCallback`, so that when the user tries to change the view it does not render a single frame on the new view (it is still not possible to change the view while the plugin is running, at least on Xplane 10.35).
* Added a command (*opentrack/toggle*) to disable the plugin from inside the sim.
* Added a command (*opentrack/toggle_translation*) to disable only the traslational components, so that we can still move around if OT only provides the rotations.
* Reinitialize the translational offsets when we re-enable the plugin, so that we can disable the plugin, move around (a long distance), and then re-enable the plugin in the new position.

Small improvements to the x-plane plugin

---

filter-kalman/CMakeLists.txt
filter-kalman/ftnoir_filter_kalman.h
filter-kalman/kalman.cpp

Meanwhile I attempted to fix the Kalman filter.
It turned out to be an issue with the timer. Possibly, the return value was assumed to be of a different unit than it really is. 
Rather than fixing the use of the QT timer, I instead replaced it with your `Timer` class for consistency.
Tbh. I'm a bit disappointed by the praised Kalman filter. It reacts either extremely slowly or it overshoots and comes back close to the real position in a very jittery way. That makes me want to try to make the process noise dependent on the predicted movement speed ... 
Also pinging @dbaarda

Kalman filter

---

gui/options-dialog.cpp
gui/options-dialog.hpp
gui/options-dialog.ui
logic/work.cpp
logic/work.hpp

I didn't like it, considering it is mostly intended as a developer aid.
With this patch, the enable button is still there, but the edit field and the button are gone.
The file select dialog will pop up when the tracker starts.
The code is simpler, too.

tracklogging: begone file selector gui

---

gui/main-window.cpp

Small inconsistency here, the prototype is now:
static void options::detail::bundler::refresh_all_bundles()
So I remove the argument. Compilation fixed.

Fix small compilation issue

---

tracker-steamvr/steamvr.cpp

Use well known matrix to euler decomposition formula, fixing some incorrect accesses. May need gimbal lock avoidance.
Don't use opentrack centering as ResetSeatedZeroPose preserves calibrated real world up (Y) vector.
Note: controllers are centered to HMD seated position.
fixes most remaining issues in #352

tracker/steamvr: Fix rotation issues

---

cmake/opentrack-boilerplate.cmake
cmake/opentrack-install.cmake

my specs `Linux Mint 18.2 Sonya` based on `Ubuntu 16.04 LTS` `Cmake 3.5.1` `gcc (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904`
On my system i have only en and ru localizations. When build opentrack target `i18n` i got error for for **nl_NL** 
```
make[2]: /usr/lib/x86_64-linux-gnu/cmake/Qt5/../../../bin/lrelease: command not found
```
On linux Qt5 cmake files located on `/usr/lib/x86_64-linux-gnu/cmake/` and Qt binaries located on `/usr/bin/`. For generating locales for **nl_NL**  cmake need lrelease and lupdate binaries. I fixed binaries path for linux target on cmake files.
I build on Linux, macOS and Windows. Also i tested this commit with my previous PL https://github.com/opentrack/opentrack/pull/668 to prevert conflicts.

fixed qt binaries location for linux

---

compat/nan.cpp
compat/timer.cpp
qxt-mini/qxtglobalshortcut_mac.cpp
spline/spline.cpp

My specs: 
`macOS 10.12.6 Sierra` `Apple LLVM version 8.1.0 (clang-802.0.42)` `Cmake 3.9.0` `Xcode 8.3.3`
When i try build on macos using Clang i got some errors.
First on `opentrack/compat/timer.cpp:112:15`
```
error: return type of out-of-line definition of 'Timer::otr_clock_gettime' differs from that in the declaration
double Timer::otr_clock_gettime(timespec* ts)
```
_fixed by changing return type as declarated_.
Then i got linker errors for libopentrack-compat 
```
Undefined symbols for architecture x86_64:
"isinf", referenced from:
_nanp in nan.cpp.o
"isnan", referenced from:
_nanp in nan.cpp.o
ld: symbol(s) not found for architecture x86_64
```
_fixed by using  `isnan(double)` and `isinf(double)` from `<math.h>`_. This fix only for APPLE target.
Next error …

fixed macos build

---

x-plane-plugin/plugin.c

This fixes the plugin loading in an undefined state. See https://forums.x-plane.org/index.php?/forums/topic/138529-psa-check-your-int-xpluginenable-function-definition/ for more information

Fix XPluginEnable

---

tracker-wii/wiiyourself/wiimote.cpp

Hey,
The build emits a ton of warnings due to unbalanced parentheses in the original `IF_TYPE` definition. I used `__VA_ARGS__` to get around it. I also fixed some of the worst compile-time warnings.
I'd like to run `clang-format` on wiiyourself while preserving line authorship information. In the farther future, I'd like to add a wrapper similar to `std::shared_ptr` for `HANDLE` types, etc. so that they never leak with the user not needing to release them manually.
Please see if this set of changes broke anything. I have no wiimote to check.

wiiyourself worst problems

---

cmake/msvc.cmake
cmake/opentrack-platform.cmake

Thus making default MSVC build working with default OpenCV static library build.
Closes #920.

Using standard _ITERATOR_DEBUG_LEVEL by default

---

tracker-freepie-udp/ftnoir_tracker_freepie-udp.cpp

I noticed that in clang the datagram packed was expected to be 52byte. However the structure that is actually going over the wire is 50 byte.
This MR makes sure that on clang we also use the packed data structure

FreePIE Use packed struct with clang to receive datagram

---

proto-wine/ftnoir_protocol_wine_dialog.cpp

Proton 5.0 has been released recently. This extends the list of Proton version with the new version number.

proto/wine: add Proton 5.0 version number

---

filter-accela/ftnoir_filter_accela.cpp
filter-ewma2/ftnoir_filter_ewma2.cpp

When crossing the border on Yaw or Roll +/-180 degrees, the Octopus makes a full rotation of 360 degrees. This made it difficult to use an inertial tracker in a wireless VR.

Fix the jump of Yaw and Roll when crossing the border +/-180 degrees

---

spline/spline-widget.cpp
tracker-pt/FTNoIR_PT_Controls.ui
tracker-pt/ftnoir_tracker_pt_dialog.cpp
tracker-pt/lang/nl_NL.ts
tracker-pt/lang/ru_RU.ts
tracker-pt/lang/stub.ts
tracker-pt/lang/zh_CN.ts
tracker-pt/module/point_extractor.cpp
tracker-pt/module/point_extractor.h
tracker-pt/pt-settings.hpp

Instead of just selecting the red/green/blue channels, also subtract the
other channels. This allows for point tracking with just colored spots,
rather than IR LEDs -- green and magenta work particularly well for
this.
This keeps the existing "Red/Green/Blue only" options, but adds
"Red/Green/Blue/Cyan/Yellow/Magenta chroma key" options, which do a better
job of isolating those colors.

Add proper color keying to tracker-pt

---

proto-wine/ftnoir_protocol_wine.cpp

Sorry, seems this `else` was accidentally deleted in my last PR.  Without it the
wineprefix keeps getting set to ~/.wine

Only set the wineprefix if not using proton

---

tracker-linux-joystick/CMakeLists.txt
tracker-linux-joystick/ftnoir_tracker_linux_joystick.cpp
tracker-linux-joystick/ftnoir_tracker_linux_joystick.h
tracker-linux-joystick/ftnoir_tracker_linux_joystick_controls.ui
tracker-linux-joystick/ftnoir_tracker_linux_joystick_dialog.cpp
tracker-linux-joystick/lang/nl_NL.ts
tracker-linux-joystick/lang/ru_RU.ts
tracker-linux-joystick/lang/stub.ts
tracker-linux-joystick/lang/zh_CN.ts
tracker-linux-joystick/linux_joystick.cpp

Add support for Linux joystick devices, this allows things like the EDTracker to
work, and possibly other devices.
I have only tested this in the Opentrack GUI so far, but all movements works.  There are some limitations, like only supporting 8 axes like the windows API.
To give a bit of context, I'm using the sysfs interface to find the joysticks because that will give me access to the device id, which is being stored in the guid field of the settings struct (like the windows version)  This GUID is then used to find the joystick when starting the driver, so that each time you click start it will find the joystick instead of hard coding the joystick device which could change.
This could be improved by reading the joystick information that comes from the joystick initialisation, but …

Add Linux Joystick Support

---

filter-hamilton/CMakeLists.txt
filter-hamilton/OTнастройки.txt
filter-hamilton/ReadMe.txt
filter-hamilton/ftnoir_filter_hamilton.cpp
filter-hamilton/ftnoir_filter_hamilton.h
filter-hamilton/ftnoir_filter_hamilton_dialog.cpp
filter-hamilton/ftnoir_hamilton_filtercontrols.ui
filter-hamilton/hamilton-tools.cpp
filter-hamilton/hamilton-tools.h
filter-hamilton/lang/nl_NL.ts
filter-hamilton/lang/ru_RU.ts
filter-hamilton/lang/stub.ts
filter-hamilton/lang/zh_CN.ts

Hamilton filter key features:
- Instead of square, round (spherical) floating dead zones and smoothing areas are applied. Due to this, the angular size of these zones does not change when the Pitch angle changes. Diagonally rotations is as easy as moving along the Yaw and Pitch axes.
- Rotations are not filtered by independent coordinates, but comprehensively, in 3D space. Rotations and movements are more natural. There are no view jumps at the borders of +/- 180 degrees.
- The possibility of increasing the smoothing of rotations when zooming (when the head is approaching the monitor, that is, when increasing the -Z coordinate) is introduced. This makes it possible to more accurately aim and monitor remote targets.
A full description of the Hamilton filter is available in Russian here: …

Add a new Hamilton filter

---

tracker-easy/tracker-easy.cpp

Thus notably fixing badly broken Z component in translation vector.
Close #1141
Close #1020

tracker/easy: Disable Kinect distortion coefficients usage

---

cmake/FindONNXRuntime.cmake
tracker-neuralnet/CMakeLists.txt
tracker-neuralnet/ftnoir_tracker_neuralnet.h

A proposal for minor changes to support system wide install though ONNXRuntime standard cmake module. (Tested on linux).
Set `ONNXRuntime_ROOT` for local build, i.e `cmake -DONNXRuntime_ROOT=/path/to/install`
NOTE: This PR provides a minimal working ONNXRuntime cmake module (request only `libonnxruntime.so`, no other components checked (providers, etc...). Official package may provide `ONNXRuntimeConfig.cmake` in the future.
See bellow to how to build and test the tracker with microsoft/ONNXRuntime (the cmake way)
```sh
git clone --single-branch --branch v1.8.1 git@github.com:microsoft/onnxruntime.git
cd onnxruntime
git submodule update --init --recursive
cmake -B workdir \
-DCMAKE_BUILD_TYPE=Release 
-DCMAKE_C_COMPILER=clang \
-DCMAKE_CXX_COMPILER=clang++ \ …
```

Tracker neuralnet update onnxrt cmake (linux)

---

cmake/FindONNXRuntime.cmake
tracker-neuralnet/CMakeLists.txt

@sthalik , here is the promised follow-up PR. There were a few things that should be corrected. I didn't notice before. Now the find script feels like overkill. Otoh it also finds the DLL which is nice. And the import target is nice, too. Suppose it is the right approach for modern CMake.
Please review.
Have to check the latest iteration on windows.
Here is an overview of the changes
* Add ONNXRuntime_DIR variable
* Change target name to onnxruntime::onnxruntime following naming
conventions for imported libs
* Look for the DLL on windows and store it in a variable for later
* Correctly define the properties of the import library
* Change names and logic for global variables to follow standard conventions
@gdolle FYI

cmake: improve the FindONNXRuntime script and install the ONNX dll

---

gui/lang/nl_NL.ts
gui/lang/ru_RU.ts
gui/lang/stub.ts
gui/lang/zh_CN.ts
gui/settings-dialog.ui
gui/settings.cpp
logic/main-settings.hpp
logic/pipeline.cpp
logic/pipeline.hpp

Opentrack now uses several centering methods.
Select the centering method from the drop-down list: `[Options] - [Shortcuts] - "Centering method"`.
- **Disabled**: Centering is disabled.
- **Point**: Point centering, the same as in OT-2.3.10, but without jumps when crossing the border +/- 180 degrees. Well suited for video trackers, although near the input |Pitch| = 90 it has strange behavior similar to "gimbal lock".
- **Wireless VR 360**: Centering using a centering matrix or quaternion, the same as in OT-2.3.11...OT-2.3.13. Ideal for wireless VR headset for 360 degree viewing, no "gimbal lock". But it requires precise installation of the sensor or clip on the head so that in the central position the Roll angle on the "Raw tracker data" panel is close to zero.
- **Roll compensated VR …

Adding a choice of centering method

---

pose-widget/pose-widget.hpp
video-opencv/impl-camera.cpp

Noticed that video capture was broken after updating the OpenCV version. This PR brings back the `video_capture_backend` variable which is still defined, but has been unused for a while it seems. Now it's working again for me.
The other thing with the initialization looks harmless. The extra copy was not needed though. And my compiler complained about it.

Fix video capture on linux and mac as well as init of QCheckBox

---

README.md

The readme states that Opentrack supports output to the X-Plane plugin. However, it is not documented anywhere that this is actually accomplished via the Wine output mode, leaving users [potentially confused](https://github.com/opentrack/opentrack/issues/1172) as to how to build Opentrack to enable an X-Plane output mode. I added a short note to this effect, which should steer would-be users in the right direction.
This resolves the above-mentioned issue 1172.

Adds a note regarding X-Plane plugin output (issue 1172)

---

migration/migration.cpp
migration/migration.hpp
video/camera.cpp

Hi,
I think there are some issues. There is this migration thingy ...
It is initialized in the dynamic initialization phase and it accesses this `migration_thunks` vector you see me change in the PR.
The vector must be initialized, too, but to my knowledge this was not guaranteed to have happended. The order between different translation units would be up to the tooling. See https://en.cppreference.com/w/cpp/language/initialization, Sec Dynamic Initialization (3).
In my case, asserts in the windows debug CRT memory management functions were triggered. 
This patch seems to fix it. I replaced the global static vars with local static vars which would be initialized on first use. c++11 makes this thread safe, too. See https://en.cppreference.com/w/cpp/language/storage_duration#Static_local_var …

Fix initialization order issues in migration code

---

x-plane-plugin/plugin.c

In X-Plane 12, pressing a key bound for any of two x-plane-plugin toggles can result in significant unexpected camera base offset shift, which can be mildly annoying.
The cause of this is X-Plane generating a rapid stream of keypress events while the key is being held down, which together with current logic of keeping camera base offset when disabling head tracking results in this problem. 
An easy fix to this is only processing an initial key press and ignoring subsequent similar events until key is released. Such check is added in this pull request.
Tested in X-Plane 12 with plugin compiled against SDK 3.0.3 and SDK 4.0.0b1 on 64bit Linux. No other tests were performed. I invite @you to comment below if you can confirm that this fix works ok on any other platform or in XP11.

x-plane-plugin update for X-Plane 12

---

CMakeLists.txt
tracker-neuralnet/CMakeLists.txt
tracker-neuralnet/model_adapters.cpp
tracker-neuralnet/model_adapters.h

* Remove tracker-neuralnet cmake code that prevents building on Linux.
* Update onnxruntime calling code for its API changes. onnxruntime has changed GetInputName/GetOutputName to GetInputNameAllocated/GetOutputNameAllocated in API version 12. Add compiling macro tests for that.
Fix issue #1559.

tracker/neuralnet: Add support for building on Linux.

---

tracker-pt/FTNoIR_PT_Controls.ui
tracker-pt/ftnoir_tracker_pt_dialog.cpp
tracker-pt/ftnoir_tracker_pt_dialog.h
tracker-pt/lang/nl_NL.ts
tracker-pt/lang/ru_RU.ts
tracker-pt/lang/stub.ts
tracker-pt/lang/zh_CN.ts
tracker-pt/module/point_extractor.cpp
tracker-pt/module/point_extractor.h
tracker-pt/pt-settings.hpp

I have been trying to use chroma key to isolate the light from green LEDs on my headset clip. However the middle of the LEDs is so bright that it is overexposed on the camera and the color fades to white. i.e. I get white blobs with green halos. The chroma key logic sees this as dark blobs surrounded by light halos. This confuses the subsequent thresholding logic. I can turn down the camera exposure but this results in very small blobs and these decrease point tracker's accuracy.
This PR adds an option for chroma key to detect overexposed pixels as the requested color when using any of the chroma key colors. This works really well.
Using green as an example, the logic change is...
Existing logic: every pixel is transformed to a grayscale value with the formula `G - 0.5 * (R + B)`. (Where …

Improved chroma key for point tracker

---

filter-hamilton/ftnoir_filter_hamilton.cpp
filter-hamilton/ftnoir_filter_hamilton.h
filter-hamilton/ftnoir_hamilton_filtercontrols.ui
filter-hamilton/lang/nl_NL.ts
filter-hamilton/lang/ru_RU.ts
filter-hamilton/lang/stub.ts
filter-hamilton/lang/zh_CN.ts

This PR began with some ideas about fixing the hamilton filter. After some discussion we concluded that there wasn't a great deal that needed fixing but some better documentation would be beneficial. This PR now addresses that along with a slight improvement in the `alpha` calculation logic. Also, whilst I was at it, I converted some tab indents to spaces to match the surrounding code.
See full discussion with @GO63-samara in #1666.
As documented (in Russian but easily google translatable) [here](https://sites.google.com/site/diyheadtracking/home/opentrack/opentrack-hamilton-filter), the alpha value calculated for the hamilton filter should have the following curves:
It actually has this:
(where, in this case, dead zone is 1.0 and max distance is 10.0)
This PR the logic and the new curves …

Hamilton documentation and minor fixes

---

compat/process-list.hpp
gui/CMakeLists.txt

I've tried to make the changes needed for procps-ng 4.0. This is the first time I touch any procps related code. I'm not sure how good are the changes. Needs testing.

Migrate to procps-ng 4.0

---

tracker-tobii/CMakeLists.txt
tracker-tobii/tobii.cpp

Downgrade SDK to v2 to support 32-bit build

tracker/tobii: Downgrade SDK to v2

---

tracker-neuralnet/ftnoir_tracker_neuralnet.cpp

Hi @sthalik ,
this should fix the 180 degree roll offset of the NN tracker. (https://github.com/opentrack/opentrack/issues/1728)
Actually I've been playing with it based on an older master branch. So, unless you changed something related in the meantime, I'm pretty confident it'll do the trick.

tracker/nn: Fix 180 deg roll

---

proto-wine/ftnoir_protocol_wine.cpp

`connected_game` is only declared in a specific configuration.

Fix build for wine without wrapper

---

tracker-neuralnet/deadzone_filter.cpp
tracker-neuralnet/model_adapters.cpp
tracker-neuralnet/model_adapters.h

This PRs main purpose is to add support for 3x3 covariance matrices for position+size estimation.
My recent (unreleased) models output those instead of only component wise standard deviations.
Overall
- Accept 3x3 covariance matrix output for position+size
- Old models still worked fine in my testing
- Delete commented code which was there previously to support recurrent models. (Won't be used in foreseeable future)
- Delete leftover code for experiments with closed eyes detection (Likewise, I have given up on that / Is not really needed any more)
- Improve comments and code quality in the internal filter code

tracker/nn: Add support for 3x3 pos/size cov matrix (and some cleanup)

---

filter-accela-hamilton/CMakeLists.txt
filter-accela-hamilton/accela_hamilton.cpp
filter-accela-hamilton/accela_hamilton.h
filter-accela-hamilton/accela_hamilton_dialog.cpp
filter-accela-hamilton/accela_hamilton_filtercontrols.ui
filter-accela-hamilton/accela_hamilton_settings.hpp
filter-accela-hamilton/lang/nl_NL.ts
filter-accela-hamilton/lang/ru_RU.ts
filter-accela-hamilton/lang/stub.ts
filter-accela-hamilton/lang/zh_CN.ts

As promised a while ago, here is a filter which combines the Accela gain curves with the rotation-space based filtering from the Hamilton filter. I hope it could maybe replace both the Accela and Hamilton filters.
Basically it applies the accela gain to the rotation vector magnitude of the shortest rotation between the current orientation and the measured orientation.
The position calculation is like in the Accela Filter.
I also included a smoothing amplification depending on the z-position. In my version I add to the smoothing amount. In the Hamilton Filter, I think the gain curve was modified which I wouldn't know how to do in the Accela way.
Maybe I could delete some of the disabled code for a spline GUI. Then again, it might be useful for tweaking those gain curves to those who know …

Combine Accela Filter with Hamilton Filter

---

proto-wine/ftnoir_protocol_wine.cpp
proto-wine/ftnoir_protocol_wine_dialog.cpp
proto-wine/proton.cpp

From Proton 9.0 and up, the directory containing library files and wine executable - previously called `dist`, appears to have been renamed to `files`. This breaks OpenTrack with newer Proton versions, because the path to the `wine` executable and proton library files is constructed as `:PROTON_PATH/dist/bin/wine`, so the executable is never found and tracking cannot be launched.
Proton 8.0 (note `dist`):
```bash
kiril@localhost ~/.l/s/S/s/common> ls Proton\ 8.0/
dist/       filelock.py*  LICENSE.OFL*  proton*                    proton_dist.tar*  toolmanifest.vdf*         version*
dist.lock*  LICENSE*      PATENTS.AV1*  proton_3.7_tracked_files*  __pycache__/      user_settings.sample.py*
```
Proton 9.0 (Beta) (`dist` is replaced by `files`):
```bash
kiril@localhost ~/.l/s/S/s/common> ls …
```

Fix compatibility with Proton 9.0 and up

---

filter-accela-hamilton/accela_hamilton.cpp
filter-accela-hamilton/accela_hamilton.h

Self explanatory.
Reason: strange stuttering motion after a while that I observed with this filter, but not with Accela.
Also, the Accela and Hamilton filter are written in double precision. So it's probably better to not take chances for bad result due to limited precision of float.
Maybe it's confirmation bias but I think the output is nice and smooth now.
Thanks @tombrazier and @GO63-samara for the math library :-D

filter/accelahamilton: rewrite in double precision

---

proto-wine/proton.cpp

Steam installer on Ubuntu places its files in $HOME/.steam/debian-installation/
This patch fixes error: "Couldn't find steam runtime"

proto-wine: Add search paths for debian-installation

---

proto-wine/ftnoir_protocol_wine.cpp
proto-wine/ftnoir_protocol_wine.h
proto-wine/ftnoir_protocol_wine_dialog.cpp
proto-wine/ftnoir_winecontrols.ui
proto-wine/lang/de_DE.ts
proto-wine/lang/nl_NL.ts
proto-wine/lang/ru_RU.ts
proto-wine/lang/stub.ts
proto-wine/lang/zh_CN.ts
proto-wine/proton.cpp
proto-wine/proton.h

RFC: #1923 
The proto-wine module has Proton support but it only allows Proton to be used within Steam. With the introduction of UMU and the shift of GloriousEggroll towards Proton the current feature support may no longer be adequate.
The UI has been changed to allow the user to specify a Proton Prefix or keep on utilizing the already existing Steam Application ID mechanism.
Elements that are not in use or relevant to the current functionality are also now being disabled.
Additionally the `make_steam_environ(proton_path, appid)` function has been split up into `make_steam_environ(proton_path)` and `make_wineprefix(appid)` to continue using the steam environment independently from the appid.
The `wine::initialize()` function has been refactored to make use of the above changes and add …

Extend Proton Support in the proto-wine module

---

tracker-neuralnet/CMakeLists.txt
tracker-neuralnet/ftnoir_tracker_neuralnet.h

Hi @sthalik 
I think it is time to update the neuralnet models.  :-)
For one I removed `head-pose.onnx`. I think the newer models are better. Personally I don't use it any more.
Then I added `head-pose-0.3-big-quantized.onnx`. It is the same architecture as `head-pose-0.2`. Performance in terms of accuracy should be very similar. However this one was "quantized" after training, i.e. the convolution ops were converted so they use integer computations. On my machine this reduces inference time to 70% of the float32 model with negligible accuracy loss.
The mobilenet variant suffered quite a big hit which is why only the big model is updated.
I left `head-pose-0.2` in place because I don't know if the quantized model has universally better performance on all hardware. To get some user …

tracker/nn: Update models

---

proto-libevdev/ftnoir_protocol_libevdev.cpp

This fixes Euro Truck Simulator 2 on linux not detecting the libevdev joystick receiver.

Give evdev arbitrary bustype vendor product and version ids

---

tracker-neuralnet/ftnoir_tracker_neuralnet.cpp
tracker-neuralnet/ftnoir_tracker_neuralnet.h

This PR is an attempt to add more FPS options to the neuralnet tracker.
@sthalik , or anyone, is this all I need to change?
I check that the fps is passed to your `camera::start`. That's okay.
But on linux my (cheap) webcam was still fixed at 30 fps and the trackhat cam at 60 fps. Need to check on windows.

tracker/nn: Add more fps options
